# Generated by Django 3.0.2 on 2020-01-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggressor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('age_max', models.IntegerField(verbose_name='Edad Max')),
                ('occupation', models.TextField(verbose_name='Ocupacíon')),
                ('victimRel', models.TextField(verbose_name='Relacion con victima')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'agresor',
                'verbose_name_plural': 'agresores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'distrito',
                'verbose_name_plural': 'distritos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.IntegerField(verbose_name='Codigo Municipio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.District', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeAggression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'tipo_agresión',
                'verbose_name_plural': 'tipo_agreciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('age_max', models.IntegerField(verbose_name='Edad Max')),
                ('occupation', models.TextField(verbose_name='Ocupacíon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'victima',
                'verbose_name_plural': 'victimas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Aggression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('observations', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('informer', models.CharField(max_length=200, verbose_name='Denunciante')),
                ('source', models.CharField(max_length=200, verbose_name='Fuente')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('detail', models.CharField(max_length=200, verbose_name='Detalle')),
                ('alleged_mobile', models.CharField(max_length=200, verbose_name='Presunto_Movil')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('aggression_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.TypeAggression', verbose_name='Tipo_agresion')),
                ('aggressors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Aggressor', verbose_name='Agresores')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Site', verbose_name='Lugar')),
                ('victim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miapp.Victim', verbose_name='Victima')),
            ],
            options={
                'verbose_name': 'agreción',
                'verbose_name_plural': 'agreciones',
                'ordering': ['name'],
            },
        ),
    ]
