# Generated by Django 3.0.2 on 2020-01-15 19:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20200115_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggressor',
            name='age_max',
        ),
        migrations.AlterField(
            model_name='aggression',
            name='aggressors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.Aggressor', verbose_name='Agresores'),
        ),
        migrations.AlterField(
            model_name='aggression',
            name='alleged_mobile',
            field=models.CharField(max_length=200, null=True, verbose_name='Presunto_Movil'),
        ),
        migrations.AlterField(
            model_name='aggression',
            name='detail',
            field=models.CharField(max_length=200, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='aggression',
            name='informer',
            field=models.CharField(max_length=200, null=True, verbose_name='Denunciante'),
        ),
        migrations.AlterField(
            model_name='aggressor',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='age_max',
            field=models.IntegerField(null=True, verbose_name='Edad Max'),
        ),
    ]
