# Generated by Django 3.0.2 on 2020-01-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20200115_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggression',
            options={'ordering': ['name'], 'verbose_name': 'agresión', 'verbose_name_plural': 'agresiones'},
        ),
        migrations.AlterField(
            model_name='aggressor',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='Edad'),
        ),
    ]
